language: node_js

node_js:
    - "8"

install:
    - npm install

script:
    - npm run docs:build

cache:
    directories:
        - "node_modules"

after_script:
  - cd ./dist
  - git init
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "deploy"
  - git push -f git@github.com:lf7817/blog.git master:gh-pages
  # - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}
  
branches:
  only:
    - master
